# Generated by Django 6.0.4 on 2026-04-09 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department')),
            ],
            options={
                'db_table': 'designations',
                'ordering': ['level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-time employee'), ('INTERN', 'Intern'), ('CONTRACT', 'Contractor'), ('CONSULTANT', 'Consultant')], default='FULL_TIME', max_length=20)),
                ('date_of_joining', models.DateField()),
                ('probation_status', models.CharField(choices=[('ON_PROBATION', 'On probation'), ('CONFIRMED', 'Confirmed'), ('NOTICE_PERIOD', 'On notice period')], default='ON_PROBATION', max_length=20)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, choices=[('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated'), ('CONTRACT_END', 'Contract ended'), ('INTERNSHIP_END', 'Internship ended')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.designation')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['employee_id'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads_department', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=50)),
                ('old_value', models.JSONField(null=True)),
                ('new_value', models.JSONField(null=True)),
                ('changed_via', models.CharField(choices=[('AGENT', 'Via chatbot/agent'), ('DASHBOARD', 'Via web dashboard'), ('ADMIN', 'Via Django admin'), ('API', 'Via direct API call'), ('IMPORT', 'Via bulk import')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_change_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_team', to='employees.employee')),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('match_employment_type', models.CharField(blank=True, max_length=20)),
                ('priority', models.IntegerField(default=10)),
                ('actions', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('match_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department')),
                ('match_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.designation')),
                ('match_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.team')),
            ],
            options={
                'db_table': 'onboarding_templates',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='employees.team'),
        ),
        migrations.CreateModel(
            name='PendingHRAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('DEPARTMENT_CHANGE', 'Employee moved to a different department'), ('MANAGER_CHANGE', 'Reporting manager changed'), ('CONFIRMATION', 'Employee confirmed (probation ended)'), ('NOTICE_PERIOD', 'Employee on notice period'), ('EXIT', 'Employee deactivated'), ('TEAM_CHANGE', 'Employee added/removed from a team'), ('DESIGNATION_CHANGE', 'Designation changed'), ('NEW_JOINER', 'New employee added — verify onboarding'), ('MANAGER_ON_LEAVE', 'Manager with pending approvals went on leave')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('affected_overrides', models.JSONField(default=list)),
                ('affected_requests', models.JSONField(default=list)),
                ('suggested_actions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('OPEN', 'Needs HR attention'), ('RESOLVED', 'HR took action'), ('DISMISSED', 'HR reviewed, no action needed'), ('AUTO_RESOLVED', 'Resolved by a subsequent action')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'Urgent — affects active requests'), ('MEDIUM', 'Should review soon'), ('LOW', 'Informational')], default='MEDIUM', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_hr_actions', to='employees.employee')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
            ],
            options={
                'db_table': 'pending_hr_actions',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(condition=models.Q(('status', 'OPEN')), fields=['status', 'priority'], name='idx_hr_action_open')],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'is_active'], name='idx_emp_dept_active'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['reporting_manager', 'is_active'], name='idx_emp_manager_active'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['probation_status'], name='idx_emp_probation'),
        ),
    ]
