# Generated by Django 4.2.27 on 2026-04-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("slack", "Slack"),
                            ("whatsapp", "WhatsApp"),
                            ("web", "Web"),
                            ("api", "API"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Connector-specific config."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bot",
                "db_table": "bot_bot",
            },
        ),
        migrations.CreateModel(
            name="ConversationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=200)),
                ("employee_id", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=20)),
                ("messages", models.JSONField(default=list)),
                ("tool_calls_count", models.IntegerField(default=0)),
                ("llm_calls_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="bot.bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Log",
                "db_table": "bot_conversation_log",
            },
        ),
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("local", "Local"),
                            ("anthropic", "Anthropic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="e.g. gpt-4o, xlam, gemma", max_length=100
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Leave blank for OpenAI. Set for local models.",
                    ),
                ),
                (
                    "api_key_env",
                    models.CharField(
                        blank=True,
                        default="OPENAI_API_KEY",
                        help_text="Environment variable name for the API key.",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Provider",
                "db_table": "bot_llm_provider",
            },
        ),
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pipeline",
                "db_table": "bot_pipeline",
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "template",
                    models.TextField(
                        help_text="Available variables: {name}, {emp_id}, {dept}, {designation}, {manager}, {today}, {leave_year}, {role}, {user_message}, {tool_results}, {previous_output}"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prompt",
                "db_table": "bot_prompt",
            },
        ),
        migrations.CreateModel(
            name="ToolCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(max_length=200)),
                ("arguments", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("employee_id", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=20)),
                ("llm_provider", models.CharField(max_length=100)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_calls",
                        to="bot.bot",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_calls",
                        to="bot.conversationlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Call Log",
                "db_table": "bot_tool_call_log",
            },
        ),
        migrations.CreateModel(
            name="PipelineStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(help_text="Execution order. Lower runs first."),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("system_prompt", "System Prompt"),
                            ("tool_call", "Tool Call"),
                            ("reply", "Reply"),
                            ("classify", "Classify"),
                            ("validate", "Validate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "role_filter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "All Roles"),
                            ("EMPLOYEE", "Employee Only"),
                            ("MANAGER", "Manager Only"),
                            ("ADMIN", "Admin Only"),
                        ],
                        default="",
                        help_text="Only run this step for this role. Blank = all roles.",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Step config. tool_call: {"tool_choice": "auto", "max_rounds": 10}. reply: {"max_tokens": 500}.',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "llm_provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="LLM to use for this step. Not needed for system_prompt steps.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_steps",
                        to="bot.llmprovider",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="bot.pipeline",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        help_text="Prompt template for this step.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_steps",
                        to="bot.prompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Step",
                "db_table": "bot_pipeline_step",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="bot",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                help_text="Pipeline that defines how this bot processes messages.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bots",
                to="bot.pipeline",
            ),
        ),
    ]
