HR_ACTION_TOOLS = [
    {
        "name": "get_pending_hr_actions",
        "description": "View HR action queue. Actions are auto-created when: new employee joins, employee exits, manager goes on leave with pending approvals, probation ends. Filter by status (OPEN/RESOLVED/DISMISSED) or priority (HIGH/MEDIUM/LOW).",
        "input_schema": {
            "type": "object",
            "properties": {
                "status": {"type": "string", "enum": ["OPEN", "RESOLVED", "DISMISSED"]},
                "priority": {"type": "string", "enum": ["HIGH", "MEDIUM", "LOW"]}
            }
        },
        "handler": "leaves.services.hr_action_service.get_pending"
    },
    {
        "name": "resolve_hr_action",
        "description": "Mark an HR action as resolved or dismissed. status defaults to RESOLVED if not specified.",
        "input_schema": {
            "type": "object",
            "properties": {
                "action_id": {"type": "integer"},
                "status": {"type": "string", "enum": ["RESOLVED", "DISMISSED"]},
                "notes": {"type": "string"}
            },
            "required": ["action_id"]
        },
        "handler": "leaves.services.hr_action_service.resolve_action"
    },
    {
        "name": "execute_suggested_action",
        "description": "Execute a system-suggested fix for an HR action. suggestion_index is 0-based (first suggestion = 0). The suggestion was generated by the system when the action was created.",
        "input_schema": {
            "type": "object",
            "properties": {
                "action_id": {"type": "integer"},
                "suggestion_index": {"type": "integer"}
            },
            "required": ["action_id", "suggestion_index"]
        },
        "handler": "leaves.services.hr_action_service.execute_suggested_action"
    },
]
