# Generated by Django 4.2.27 on 2026-04-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LEAVE_APPLIED", "Leave Applied"),
                            ("LEAVE_APPROVED", "Leave Approved"),
                            ("LEAVE_REJECTED", "Leave Rejected"),
                            ("LEAVE_CANCELLED", "Leave Cancelled"),
                            ("BALANCE_ADJUSTED", "Balance Adjusted"),
                            ("POLICY_CHANGED", "Policy Changed"),
                            ("OVERRIDE_CREATED", "Override Created"),
                            ("OVERRIDE_REMOVED", "Override Removed"),
                            ("EMPLOYEE_ADDED", "Employee Added"),
                            ("EMPLOYEE_CONFIRMED", "Employee Confirmed"),
                            ("EMPLOYEE_DEACTIVATED", "Employee Deactivated"),
                            ("EMPLOYEE_TRANSFERRED", "Employee Transferred"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "actor_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Employee ID of who performed the action",
                        max_length=20,
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Employee ID of who is affected",
                        max_length=20,
                    ),
                ),
                (
                    "target_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("ALL", "Everyone"),
                            ("HR", "HR Only"),
                            ("MANAGER", "Manager + HR"),
                            ("EMPLOYEE", "Employee + Manager + HR"),
                        ],
                        default="EMPLOYEE",
                        max_length=20,
                    ),
                ),
                (
                    "manager_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reporting manager employee ID (for manager feed filtering)",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "channels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of channels: ["web", "slack_dm", "email"]',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "notifications_activity",
                "ordering": ["-created_at"],
            },
        ),
    ]
